---
- name: get Vehicle Detection package source
  become: true
  git:
    accept_hostkey: yes
    repo: "{{ repository }}"
    dest: "{{ dev }}"
    force: yes

- name: Changing the directory
  shell: cd /dev/vehicledetection/build

- name: Running cmake
  become: yes
  shell: |
    source /usr/local/bin/virtualenvwrapper.sh
    cmake ..
  args:
    chdir: "/dev/vehicledetection/build"
    executable: /bin/bash
   
- name: Running make
  become: yes
  shell: |
    source /usr/local/bin/virtualenvwrapper.sh
    make
  args:
    chdir: "/dev/vehicledetection/build"
    executable: /bin/bash

- name: Running the demos
  become: yes
  shell: |
    source /dev/vehicledetection/run_vehicle_detection_video1.sh
  args:
    chdir: "/dev/vehicledetection"
    executable: /bin/bash
