---
- name: Checking if temporary directory exists
  stat: path={{ dwnld_dr }}
  register: tmp

- name: Creating a temporary directory for download, if not
  file: name={{ dwnld_dr }} state=directory
  when: tmp.stat.exists == false

- name: Downloading pip installer
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest={{ dwnld_dr }}

- name: Storing the full path of download directory in pwd_result
  shell: pwd
  args:
    chdir: "{{ dwnld_dr }}"
  register: pwd_result 

- name: Installing pip
  become: true
  command: python3 {{ pwd_result.stdout }}/get-pip.py
