---
- name: Check if temporary directory already exists
  stat: path={{ dwnld_dr }}
  register: tmp

- name: Create temporary download directory
  file: name={{ dwnld_dr }} state=directory
  when: tmp.stat.exists == false

- name: Download pip installer
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest={{ dwnld_dr }}

- name: Get full path of download directory ("~" varies by user)
  shell: pwd
  args:
    chdir: "{{ dwnld_dr }}"
  register: pwd_result 

- name: Install pip
  become: true
  command: python3 {{ pwd_result.stdout }}/get-pip.py

#- name: Remove temporary download directory, if it didn't prevously exist
#  file: name={{ dwnld_dr }} state=absent
#  when: tmp.stat.exists == false