---
- name: Checking if the temporary directory already exists
  stat: path={{ dwnld_dr }}
  register: tmp

- name: Creating a temporary download directory
  file: name={{ dwnld_dr }} state=directory
  when: tmp.stat.exists == false

- name: Downloading pip installer for installing Python
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest={{ dwnld_dr }}

- name: Getting the full path of download directory
  shell: pwd
  args:
    chdir: "{{ dwnld_dr }}"
  register: pwd_result 

- name: Installing pip
  become: true
  command: python3 {{ pwd_result.stdout }}/get-pip.py

#- name: Remove temporary download directory, if it didn't prevously exist
#  file: name={{ dwnld_dr }} state=absent
#  when: tmp.stat.exists == false
