---
- name: Installing developer tools
  become: true
  apt: name={{ item }} state=present
  with_items:
  - build-essential
  - cmake
  - git
  - pkg-config

- name: Installing the packages used for optimization
  become: true
  apt: name={{ item }}
  with_items:
  - libatlas-base-dev
  - gfortran

- name: Installing the Python3 headers files
  become: true
  apt: name=python3.4-dev

- name: Installing unzip for extracting OpenCV
  become: true
  apt: name=unzip

- name: Checking if the temporary directory exists
  stat: path={{ dwnld_dr }}
  register: tmp

- name: Creating temporary download directory if it does not exist
  file: name={{ dwnld_dr }} state=directory
  when: tmp.stat.exists == false

- name: Downloading and unzipping OpenCV
  unarchive: src=https://github.com/Itseez/opencv/archive/{{ ocv_ver }}.zip dest={{ dwnld_dr }} copy=no

- name: Creating a build directory
  file: name={{ dwnld_dr }}/opencv-{{ ocv_ver }}/build state=directory

- name: Making the OpenCV build objects
  shell: |
    source /usr/local/bin/virtualenvwrapper.sh
    cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_C_EXAMPLES=OFF -D INSTALL_PYTHON_EXAMPLES=ON -D OPENCV_EXTRA_MODULES_PATH={{ dwnld_dr }}/opencv_contrib-{{ ocv_ver }}/modules -D BUILD_EXAMPLES=ON ..
  args:
    chdir: "{{ dwnld_dr }}/opencv-{{ ocv_ver }}/build"
    executable: /bin/bash

- name: Compiling OpenCV
  shell: |
    source /usr/local/bin/virtualenvwrapper.sh
    make
  args:
    chdir: "{{ dwnld_dr }}/opencv-{{ ocv_ver }}/build"
    executable: /bin/bash

- name: Storing the full path of download directory in pwd_result
  shell: pwd
  args:
    chdir: "{{ dwnld_dr }}"
  register: pwd_result

- name: Installing OpenCV
  become: true
  shell: |
    source /usr/local/bin/virtualenvwrapper.sh
    make install
    ldconfig
  args:
    chdir: "{{ pwd_result.stdout }}/opencv-{{ ocv_ver }}/build"
    executable: /bin/bash
